name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build mcc
        uses: docker://sacredbanana/amiga-compiler:m68k-amigaos
        with:
          args: sh -c "cd mcc && make OS=os3 DEBUG="

      - name: Build mcp
        uses: docker://sacredbanana/amiga-compiler:m68k-amigaos
        with:
          args: sh -c "cd mcp && make OS=os3 DEBUG="

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: htmlview-os3
          path: |
            mcc/bin_os3/*.mcc
            mcp/bin_os3/*.mcp
